apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: alert-rules-manager
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad  #your alert
    - matchers:
      - name: alertname
        value: PodCrashLooping   #your alert
      repeatInterval: 10m
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'email@example.come'
      from: 'email@example.come'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'email@example.come'
      authIdentity: 'email@example.come'
      authPassword:
       name: gmail-auth
       key: password
