apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-rules
  namespace: default
  labels:
     app: prometheus-monitoring
     release: monitoring
spec:
  groups:
    - name: HostHighCpuLoad
      rules:
        - alert: HostHighCpuLoad
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 50
          for: 2m
          labels:
            severity: warning
          annotations:
            description: "CPU load is over 50%\n Value = {{  $value  }}\n Instance = {{  $labels.instance   }}"
            summary: "CPU load is high"
        - alert: PodCrashLooping
          expr: kube_pod_container_status_restarts_total > 5
          for: 0m
          labels:
               severity: critical
          annotations: 
                description: "Pod {{ $labels.pod }} is crash looping\n Value = {{ $value }}"
                summary: "Kubernetes pod crash looping"
            

